"""Tests for command-line project handling and Windows file association.

Both modules are Qt-free, and the registry layout is generated by a pure
function, so these run on any platform.
"""
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from MegaSerial import cli, file_association


class ArgumentParsingTests(unittest.TestCase):
    def setUp(self):
        self.parser = cli.build_parser()

    def test_no_arguments_means_no_project_and_no_registration(self):
        args = self.parser.parse_args([])

        self.assertIsNone(args.project)
        self.assertFalse(args.register_file_association)
        self.assertFalse(args.unregister_file_association)

    def test_a_project_path_is_taken_as_a_positional_argument(self):
        args = self.parser.parse_args([r"C:\Projects\EC200.msproj"])

        self.assertEqual(args.project, r"C:\Projects\EC200.msproj")

    def test_association_flags_are_recognized(self):
        self.assertTrue(
            self.parser.parse_args(["--register-file-association"]).register_file_association)
        self.assertTrue(
            self.parser.parse_args(["--unregister-file-association"]).unregister_file_association)


class ProjectPathValidationTests(unittest.TestCase):
    def setUp(self):
        self.directory = Path(tempfile.mkdtemp())

    def _make(self, name: str) -> Path:
        path = self.directory / name
        path.write_text("{}", encoding="utf-8")
        return path

    def test_an_existing_project_file_resolves_to_an_absolute_path(self):
        path = self._make("EC200.msproj")

        resolved = cli.resolve_project_path(str(path))

        self.assertTrue(resolved.is_absolute())
        self.assertEqual(resolved, path.resolve())

    def test_paths_with_spaces_and_unicode_are_accepted(self):
        for name in ("EC200 Test Run.msproj", "مودم تست.msproj", "naïve café.msproj"):
            with self.subTest(name=name):
                path = self._make(name)
                self.assertEqual(cli.resolve_project_path(str(path)), path.resolve())

    def test_json_projects_are_accepted_like_the_open_dialog(self):
        path = self._make("saved.json")

        self.assertEqual(cli.resolve_project_path(str(path)), path.resolve())

    def test_a_missing_file_is_rejected(self):
        missing = self.directory / "nope.msproj"

        with self.assertRaisesRegex(cli.ProjectPathError, "No such file"):
            cli.resolve_project_path(str(missing))

    def test_a_directory_is_rejected(self):
        with self.assertRaisesRegex(cli.ProjectPathError, "Not a file"):
            cli.resolve_project_path(str(self.directory))

    def test_an_unsupported_extension_is_rejected(self):
        path = self._make("notes.txt")

        with self.assertRaisesRegex(cli.ProjectPathError, "not a MegaSerial project"):
            cli.resolve_project_path(str(path))

    def test_an_empty_or_blank_path_is_rejected(self):
        for raw in ("", "   "):
            with self.subTest(raw=raw):
                with self.assertRaises(cli.ProjectPathError):
                    cli.resolve_project_path(raw)

    def test_the_suffix_check_is_case_insensitive(self):
        path = self._make("Shouty.MSPROJ")

        self.assertEqual(cli.resolve_project_path(str(path)), path.resolve())


class FileAssociationLayoutTests(unittest.TestCase):
    EXE = r"C:\Program Files\MegaSerial\MegaSerial.exe"

    def test_packaged_command_quotes_both_the_exe_and_the_clicked_path(self):
        command = file_association.launch_command(self.EXE, frozen=True)

        self.assertEqual(command, f'"{self.EXE}" "%1"')

    def test_source_command_launches_through_the_package(self):
        command = file_association.launch_command(r"C:\Python\python.exe", frozen=False)

        self.assertEqual(command, r'"C:\Python\python.exe" -m MegaSerial "%1"')

    def test_every_entry_lives_under_the_current_user_classes_root(self):
        entries = file_association.registry_entries(self.EXE, frozen=True)

        self.assertTrue(all(key.startswith(r"Software\Classes")
                            for key, _ in entries))

    def test_entries_point_the_extension_at_the_prog_id_and_the_prog_id_at_the_command(self):
        entries = dict(file_association.registry_entries(self.EXE, frozen=True))

        self.assertEqual(entries[file_association.EXTENSION_KEY],
                         file_association.PROG_ID)
        self.assertEqual(entries[file_association.PROG_ID_KEY],
                         file_association.FILE_TYPE_LABEL)
        self.assertEqual(entries[file_association.COMMAND_KEY], f'"{self.EXE}" "%1"')
        self.assertEqual(entries[file_association.ICON_KEY], f'"{self.EXE}",0')

    def test_a_source_checkout_registers_no_executable_icon(self):
        entries = dict(file_association.registry_entries("python.exe", frozen=False))

        self.assertNotIn(file_association.ICON_KEY, entries)

    def test_registering_on_a_non_windows_platform_reports_instead_of_crashing(self):
        import sys

        if sys.platform == "win32":
            self.skipTest("Windows registers for real")
        with self.assertRaises(file_association.AssociationError):
            file_association.register()
        with self.assertRaises(file_association.AssociationError):
            file_association.unregister()


if __name__ == "__main__":
    unittest.main()
